function OUTPUT = TREATMENT(INPUT)

RT_TT = retime(INPUT,'secondly', 'mean');

RT_TT = fillmissing(RT_TT, 'next');

RT_TT = STDCLEANER(RT_TT,RT_TT.MASSFLOWPOWDERDOSING1);

RT_TT.SPEEDGRANULATOR = RPM2RPS(RT_TT.SPEEDGRANULATOR);

RT_TT.ENERGY = (RT_TT.SPEEDGRANULATOR .* RT_TT.TORQUEGRANULATOR)./RT_TT.MASSFLOWPOWDERDOSING1;

OUTPUT = RT_TT;

end 